name: shopeasy
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.0.15
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  cloud_firestore_web: ^4.4.2
  flutterfire_cli: ^1.0.1

 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
